### ISSUE TITLE
Tracking Bootstrap 4 Changes

### ISSUE THREAD

**Issue by eddywashere** [reactstrap/reactstrap#33]
Here's some changes I've seen between the last release, [v4.0.0-alpha.2](https://github.com/twbs/bootstrap/tree/v4.0.0-alpha.2) and the [v4-dev](https://github.com/twbs/bootstrap/tree/v4-dev) branch
- [x] outline classes are no longer appended to classnames. ex: `.btn-primary-outline` -> `.btn-outline-primary`
- [x] Label is now Tag. ex: `.label` -> `.tag`

**Comment by eddywashere** [comment]
Moving the `outline` option to a boolean based prop from the color prop could simplify upgrading (for the Button component).

**Comment by eddywashere** [comment]
- [ ] Column offset, pull and push classes are now `.push-md-2`, `.pull-md-2`, `.offset-md-2`.

**Comment by eddywashere** [comment]
Closing this in favor of specific issues that cover a change and track the status of it.
